server:
  port: 8085
#连接数据库
spring:
  datasource:
    username: root
    password: 724933
    url: jdbc:mysql://120.48.75.156:3306/db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据源用druid
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  #MQ配置信息
  rabbitmq:
    host: 120.48.75.156
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-returns: true

  # redis 配置
  redis:
    database: 2
    iddatabase: 2
    host: 120.48.75.156
    lettuce:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8 #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: "724933"
    port: 6379
  #环境
  application:
    name: cur
  profiles:
    active: dev


#mybatis:
#  #全局配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
#  #mapper配置文件
#  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/mapper/*.xml,classpath*:mapper/*.xml,classpath*:mapper/**/*.xml

# 项目启动时自动创建表
#    schema:
#      - classpath:/sql/department.sql
#      - classpath:/sql/employee.sql
#  jpa:
#    hibernate:
#      #更新或者创建数据库表结构
#      ddl-auto: update
#      #控制台显示sql
#      show-sql: true



minio:
  url: http://192.168.1.253:9000
  accessKey: minioadmin
  secretKey: minioadmin
  minio_name: minioadmin
  minio_pass: minioadmin
  bucketName: tcyy
  #邮箱
mail:
  flag: true
  url: http://192.168.1.253:7758/mail/sendTemplateMail
  to: 522724933@qq.com

# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math